basePath: /api
definitions:
  film.FilmResponse:
    description: is the response struct
    properties:
      film:
        $ref: '#/definitions/film.FilmStruct'
      status:
        example: success
        type: string
    type: object
  film.FilmStruct:
    description: stores the film data
    properties:
      href:
        example: https://example.com/film/1
        type: string
      id:
        example: film-1
        type: string
      idParts:
        $ref: '#/definitions/film.IdSplit'
      poster:
        example: https://example.com/poster/1.jpg
        type: string
    type: object
  film.IdSplit:
    description: stores the film ID parts
    properties:
      idNum:
        type: integer
      name:
        example: Film 1
        type: string
      type:
        example: film
        type: string
    type: object
info:
  contact: {}
  description: Pipebomb API for searching and streaming movies
  title: Pipebomb API
  version: "1.0"
paths:
  /films/vip/search:
    get:
      consumes:
      - application/json
      description: Searches for a film and returns a JSON response
      parameters:
      - description: Search Query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/film.FilmResponse'
      summary: Search for a film
      tags:
      - films
swagger: "2.0"
